/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sfa.aventcode.y2021.app;

import com.sfa.aventcode.y2021.jour1.Jour1;

public class App {
    public static void main(String[] args) {
    	Jour1 j1 = new Jour1();
    	j1.parseInput();
    	j1.run();
    }
}
